schema_version: 1
include:
  - common
  - minimal
packages_add:
  - audiowrt-bluetooth
  - kmod-audiowrt-bluetooth
packages_remove:
  - kmod-bluetooth
  - kmod-btusb
  - kmod-btmtk
  - kmod-sound-core
  - kmod-sound-midi2
  - kmod-sound-midi2-usb
  - kmod-usb-audio
  - kmod-media-controller
