schema_version: 1
include:
  - minimal
packages_add:
  - audiowrt-usb-audio
  - audiowrt-bluetooth
  - kmod-audiowrt-bluetooth
  - kmod-sound-core
  - kmod-usb-audio
packages_remove:
  - kmod-bluetooth
  - kmod-btusb
  - kmod-btmtk
