schema_version: 1
include:
  - minimal
packages_add:
  - audiowrt-bluetooth
  - kmod-audiowrt-bluetooth
packages_remove:
  - audiowrt-player-mp3
  - audiowrt-player-aac
  - audiowrt-player-m4a
  - kmod-bluetooth
  - kmod-btusb
  - kmod-btmtk
  - kmod-sound-core
  - kmod-sound-midi2
  - kmod-sound-midi2-usb
  - kmod-usb-audio
