schema_version: 1
include:
  - minimal
packages_add:
  - dbus-trimmed
  - audiowrt-usb-audio
  - audiowrt-bluetooth
  - kmod-bluetooth-tailored
  - kmod-sound-core
  - kmod-usb-audio
packages_remove:
  - dbus
  - kmod-bluetooth
  - kmod-btusb
  - kmod-btmtk
