schema_version: 1
packages_add:
  - audiowrt-minimal-alsa
  - audiowrt-minimal-mbedtls
  - audiowrt-dropbear
  - audiowrt-wpa-supplicant
  - audiowrt-player-core
  - audiowrt-player-flac
packages_remove:
  - odhcp6c
  - alsa-lib
  - libmbedtls21
  - dropbear
  - wpad-basic-mbedtls
  - wpad-basic
  - wpad
  - mpd-mini
  - mpd-full
  - upmpdcli
  - audiowrt-minimal-upmpdcli
  - audiowrt-mpd
  - audiowrt-player-mp3
  - kmod-media-controller
