schema_version: 1
include:
  - minimal
packages_add:
  - audiowrt-usb-audio
  - kmod-sound-core
  - kmod-usb-audio
packages_remove:
  - audiowrt-bluetooth
  - bluez-trimmed
  - bluez-libs
  - audiowrt-btctl
  - bluez-alsa
  - sbc-trimmed
  - kmod-bluetooth-tailored
  - kmod-bluetooth
  - kmod-btusb
  - kmod-btmtk
