schema_version: 1
packages_add:
  - alsa-lib
  - libmbedtls21
  - dropbear
  - wpad-basic-mbedtls
  - audiowrt-player-core
  - audiowrt-player-flac
  - audiowrt-player-mp3
  - audiowrt-player-aac
  - audiowrt-player-wav
packages_remove:
  - audiowrt-minimal-alsa
  - audiowrt-minimal-mbedtls
  - audiowrt-dropbear
  - audiowrt-wpad
  - mpd-mini
  - mpd-full
  - upmpdcli
  - audiowrt-mpd
  - audiowrt-minimal-upmpdcli
