schema_version: 1
include:
  - standard
packages_add:
  - audiowrt-usb-audio
  - kmod-sound-core
  - kmod-sound-midi2
  - kmod-sound-midi2-usb
  - kmod-usb-audio
packages_remove:
  - audiowrt-bluetooth
  - audiowrt-bluez
  - audiowrt-bluez-libs
  - audiowrt-btctl
  - bluez-alsa
  - audiowrt-sbc
  - kmod-audiowrt-bluetooth
  - kmod-bluetooth
  - kmod-btusb
  - kmod-btmtk
