schema_version: 1
packages_add:
  - audiowrt-usb-audio
  - alsa-lib
  - libmbedtls21
  - kmod-sound-core
  - kmod-sound-midi2
  - kmod-sound-midi2-usb
  - kmod-usb-audio
  - umdns
packages_remove:
  - audiowrt-bluetooth
  - audiowrt-bluez
  - audiowrt-bluez-libs
  - audiowrt-btctl
  - bluez-alsa
  - audiowrt-sbc
  - kmod-audiowrt-bluetooth
  - kmod-bluetooth
  - kmod-btusb
  - kmod-btmtk
  - audiowrt-minimal-alsa
  - audiowrt-minimal-mbedtls
