schema_version: 1
include:
  - standard
packages_add:
  - audiowrt-usb-audio
  - audiowrt-bluetooth
  - kmod-sound-core
  - kmod-usb-audio
  - kmod-bluetooth
  - kmod-btusb
packages_remove:
  - kmod-audiowrt-bluetooth
